/* Static prototype: private data lives in this browser. No nutrition data is inferred. */
const KEY = 'weekly-table-v1';
const clone = value => JSON.parse(JSON.stringify(value));
const seed = [
  {id:'chicken',name:'雞腿排便當',category:'便當',emoji:'🍗',time:30,cost:101,description:'香煎雞腿排、蒜炒高麗菜與鴻禧菇。',ingredients:[{name:'雞腿排',qty:1,unit:'片',prep:'分餐保存，烹煮前確認已解凍'},{name:'高麗菜',qty:.25,unit:'顆',prep:'切片，炒前再切'},{name:'鴻禧菇',qty:.5,unit:'包',prep:'去根部、撥散'}],steps:['雞腿排擦乾並依喜好調味，煎至完全熟透。','高麗菜切片，鴻禧菇去根，分別炒熟。','盛飯後搭配主菜與配菜。'],storage:'生雞肉若不在短時間內烹調，按餐分裝冷凍；蔬菜保留完整，烹煮前再切。',nutrition:{}},
  {id:'cabbage-rice',name:'高麗菜飯',category:'飯食',emoji:'🍚',time:25,cost:98,description:'高麗菜、洋蔥與肉絲的一鍋飯。',ingredients:[{name:'高麗菜',qty:.5,unit:'顆',prep:'切小片'},{name:'洋蔥',qty:.25,unit:'顆',prep:'切丁或細絲'},{name:'紅蘿蔔絲',qty:150,unit:'g',prep:'洗淨備用'},{name:'豬肉絲',qty:1,unit:'份',prep:'一份約為原採買量的三分之一；分裝冷凍'}],steps:['高麗菜切片、洋蔥切丁，肉絲分裝取出。','炒香洋蔥與肉絲，再加入高麗菜、紅蘿蔔絲。','加入已煮好的飯拌勻，確認肉絲熟透。'],storage:'豬肉絲短期未煮可先分餐冷凍；已煮好的飯菜及時冷藏，勿在室溫久放。',nutrition:{}},
  {id:'potato-beef',name:'馬鈴薯燉牛肉',category:'燉煮',emoji:'🥘',time:45,cost:108,description:'用牛肉片、洋蔥與馬鈴薯煮一鍋家常燉菜。',ingredients:[{name:'牛肉片',qty:120,unit:'g',prep:'按餐分裝，烹煮前解凍'},{name:'馬鈴薯',qty:300,unit:'g',prep:'烹煮當天去皮切塊'},{name:'洋蔥',qty:.25,unit:'顆',prep:'切片'}],steps:['洋蔥切片，馬鈴薯去皮切塊。','將洋蔥與牛肉片炒香，再加入馬鈴薯及適量水。','燉至馬鈴薯變軟、牛肉完全熟透。'],storage:'馬鈴薯保持完整、放陰涼處，料理當天再切；生牛肉依包裝期限保存。',nutrition:{}},
  {id:'potato-pork',name:'馬鈴薯燉豬肉',category:'燉煮',emoji:'🍲',time:45,cost:98,description:'以豬肉取代牛肉的實惠燉煮版本。',ingredients:[{name:'豬肉',qty:125,unit:'g',prep:'按餐分裝'},{name:'馬鈴薯',qty:300,unit:'g',prep:'烹煮當天切塊'},{name:'洋蔥',qty:.25,unit:'顆',prep:'切片'}],steps:['洋蔥切片、馬鈴薯切塊。','炒香豬肉與洋蔥，加馬鈴薯和適量水。','燉至馬鈴薯軟透、豬肉完全熟透。'],storage:'生豬肉依包裝期限保存；若本週後段才煮，採買後分餐冷凍。',nutrition:{}},
  {id:'udon',name:'炒烏龍麵',category:'麵食',emoji:'🍜',time:20,cost:null,description:'洋蔥、肉絲、菇與蔬菜的快速一鍋炒麵。',ingredients:[{name:'烏龍麵',qty:1,unit:'份',prep:'依包裝方式處理'},{name:'洋蔥',qty:.25,unit:'顆',prep:'切絲'},{name:'豬肉絲',qty:1,unit:'份',prep:'一份約為原採買量的三分之一'},{name:'紅蘿蔔絲',qty:150,unit:'g',prep:'洗淨備用'},{name:'鴻禧菇',qty:1,unit:'包',prep:'去根、撥散'}],steps:['洋蔥切絲，鴻禧菇去根。','先炒熟肉絲與洋蔥，再加紅蘿蔔絲及菇。','加入烏龍麵翻炒至全部熱透。'],storage:'未使用的豬肉絲分餐冷凍；菇類依實際包裝標示及狀況使用。',nutrition:{}}
];
const defaults = () => ({recipes:clone(seed),plan:[],inventory:{},storage:{},checked:{},baseline:300,targets:{},week:1});
let state;
try {const raw=JSON.parse(localStorage.getItem(KEY));state=raw && Array.isArray(raw.recipes)&&Array.isArray(raw.plan) ? {...defaults(),...raw} : defaults()} catch {state=defaults()}
let page='plan', search='', category='全部', candidateId=null, editingId=null;
const $=s=>document.querySelector(s), app=$('#app'), dialog=$('#recipe-dialog');
const esc=v=>String(v??'').replace(/[&<>"']/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const attr=esc, money=v=>Number.isFinite(v)?'NT$'+Math.round(v).toLocaleString('zh-TW'):'待補';
const fmt=v=>Number.isInteger(v)?String(v):String(Math.round(v*100)/100);
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('儲存空間不足，這次變更可能無法保留。')}};
function toast(message){const t=$('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>t.classList.remove('show'),3000)}
const heading=(k,t,p,actions='')=>`<div class="page-kicker">${k}</div><div class="page-heading"><div><h1>${t}</h1><p>${p}</p></div>${actions}</div>`;
const btn=(action,label,cls='button',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${label}</button>`;
const selected=()=>state.plan.map(x=>x.recipe);
const remaining=()=>state.plan.filter(x=>!x.done);
const total=entries=>entries.reduce((n,r)=>n+(Number.isFinite(r.cost)?r.cost:0),0);
const allPriced=entries=>entries.every(r=>Number.isFinite(r.cost));
const costText=entries=>allPriced(entries)?money(total(entries)):(entries.length?money(total(entries))+'＋待補':'NT$0');
const invKey=(name,unit)=>name.trim().toLowerCase()+'|'+unit.trim().toLowerCase();
function requirements(entries=selected()){const map=new Map();for(const r of entries)for(const i of r.ingredients){const key=invKey(i.name,i.unit);if(!map.has(key))map.set(key,{...i,qty:0,key});map.get(key).qty+=Number(i.qty)}return [...map.values()]}
const stock=i=>Number(state.inventory[invKey(i.name,i.unit)]||0);
function card(r,mode='view',index=0){return `<article class="recipe-card"><div class="card-art" aria-hidden="true">${esc(r.emoji||'🍽️')}</div><div class="card-body"><div class="card-top"><span>${esc(r.category||'家常菜')}</span><span>約 ${esc(r.time||'?')} 分鐘</span></div><h3>${esc(r.name)}</h3><p>${esc(r.description||r.ingredients.map(i=>i.name).join('、'))}</p><div class="card-bottom"><span>每份預估</span><strong>${money(r.cost)}</strong></div><div class="card-actions">${mode==='plan'?btn('add','加入本週','button small',`data-id="${attr(r.id)}"`):mode==='today'?btn('view','查看菜卡','button small',`data-index="${index}"`):btn('view-library','查看菜色','button small',`data-id="${attr(r.id)}"`)}</div></div></article>`}
function planPage(){const picked=selected(),complete=state.plan.filter(x=>x.done).length;app.innerHTML=heading('THE WEEKLY MENU','本週想吃什麼？','先選七餐，不安排星期幾。選完後每天再決定要煮哪一道。',btn('new-week','開始新的一週','button outline small'))+`<section class="hero"><div><div class="hero-label">THIS WEEK'S TABLE</div><h2>先挑喜歡的，<br>今天吃哪道，今天再決定。</h2><p>可以重複選同一道菜。已選菜色會保存當時的食譜內容。</p></div><div class="big-symbol" aria-hidden="true">✳</div></section><div class="metrics"><div class="metric"><span>已選餐次</span><strong>${state.plan.length} / 7</strong><small>七餐不指定日期</small></div><div class="metric"><span>已經煮好</span><strong>${complete} 餐</strong><small>照自己的節奏來</small></div><div class="metric"><span>七餐預估成本</span><strong>${costText(picked)}</strong><small>有待補價格時僅顯示已知部分</small></div></div><div class="section-heading"><h2>這週的七餐</h2><span>想換菜可在煮之前移除</span></div><div class="slots">${Array.from({length:7},(_,i)=>{const slot=state.plan[i];return slot?`<article class="slot ${slot.done?'completed':''}"><div><span class="slot-number">MEAL ${String(i+1).padStart(2,'0')} · ${slot.done?'已完成':'尚未煮'}</span><h3>${esc(slot.recipe.emoji||'🍽️')} ${esc(slot.recipe.name)}</h3><p>${money(slot.recipe.cost)} · 約 ${esc(slot.recipe.time||'?')} 分鐘</p></div>${slot.done?'<span class="pill">✓ 已煮好</span>':btn('remove-plan','移出本週','button ghost small',`data-index="${i}"`)}</article>`:`<article class="slot empty"><span>＋</span><div>還有一道好菜等你選</div></article>`}).join('')}</div><div class="section-heading"><h2>從菜色庫選菜</h2><span>${state.recipes.length} 道菜色</span></div>${toolbar()}${grid(state.recipes.filter(filterRecipe),'plan')}`;bindSearch()}
function toolbar(){const cats=['全部',...new Set(state.recipes.map(r=>r.category||'家常菜'))];return `<div class="toolbar"><input id="recipe-search" class="search" type="search" placeholder="搜尋菜名或食材…" value="${attr(search)}" aria-label="搜尋菜色"><div class="filters">${cats.map(c=>`<button class="chip ${category===c?'active':''}" data-action="filter" data-category="${attr(c)}">${esc(c)}</button>`).join('')}</div></div>`}
function filterRecipe(r){return (category==='全部'||(r.category||'家常菜')===category)&&(!search||[r.name,...r.ingredients.map(i=>i.name)].join(' ').toLowerCase().includes(search.toLowerCase()))}
function grid(items,mode){return items.length?`<div class="recipe-grid">${items.map((r,i)=>card(r,mode,i)).join('')}</div>`:`<div class="empty-state"><strong>沒有符合的菜色</strong>試試其他關鍵字，或到菜色總覽新增。</div>`}
function bindSearch(){const input=$('#recipe-search');if(input)input.addEventListener('input',e=>{const start=e.target.selectionStart;search=e.target.value;render();const next=$('#recipe-search');next.focus();next.setSelectionRange(start,start)})}
function todayPage(){const todo=remaining();if(candidateId&&!todo.some(x=>x.id===candidateId))candidateId=null;const candidate=todo.find(x=>x.id===candidateId);app.innerHTML=heading('TODAY’S PICK','今天煮什麼？','從本週還沒煮的菜色挑一道，或讓抽卡幫你決定。',btn('draw','✦ 抽一道','button',todo.length?'':'disabled'))+`<div class="callout">抽卡不會替你決定今天能不能煮。菜卡會顯示食材與解凍資訊，最後由你選擇。</div>${candidate?`<div class="section-heading"><h2>抽到這一道</h2><span>不喜歡可以再抽一次</span></div><div class="recipe-grid">${card(candidate.recipe,'today',state.plan.findIndex(x=>x.id===candidate.id))}</div>`:''}<div class="section-heading"><h2>本週還沒煮的菜</h2><span>${todo.length} 道待選</span></div>${todo.length?`<div class="recipe-grid">${todo.map(x=>card(x.recipe,'today',state.plan.findIndex(p=>p.id===x.id))).join('')}</div>`:`<div class="empty-state"><strong>${state.plan.length?'本週菜色都煮完了！':'還沒有選本週菜色'}</strong><a href="#plan">前往本週七餐選菜 →</a></div>`}`}
function shoppingPage(){const items=requirements(remaining().map(x=>x.recipe));const all=requirements(), deficit=items.filter(i=>Math.max(0,i.qty-stock(i))>0);app.innerHTML=heading('SHOP & PREP','採買與保存','相同名稱與單位的食材會合併；輸入家中現有量後，清單會更新。')+`<div class="two-col"><div class="panel"><h2>這週需要採買</h2><p class="note">以下是尚未煮餐點的需求量，扣除你手動登記的現有量。勾選僅作為購物標記，不會自動增加庫存。</p>${deficit.length?deficit.map(i=>`<label class="shop-row ${state.checked[i.key]?'done':''}"><span><strong>${esc(i.name)}</strong><small>需要 ${fmt(i.qty)} ${esc(i.unit)} · 現有 ${fmt(stock(i))} ${esc(i.unit)}</small></span><span><strong>買 ${fmt(Math.max(0,i.qty-stock(i)))} ${esc(i.unit)}</strong><input type="checkbox" data-shop="${attr(i.key)}" ${state.checked[i.key]?'checked':''}></span></label>`).join(''):`<div class="empty-state"><strong>目前沒有待採買食材</strong>先選七餐，或更新家中現有量。</div>`}</div><div class="panel"><h2>家中現有食材</h2><p class="note">單位需與食譜一致才能抵扣。可登記保存方式與包裝期限；系統不會替你推測到期日。</p>${all.length?all.map(i=>`<div class="list-row"><span><strong>${esc(i.name)}</strong><small>單位：${esc(i.unit)}</small></span><span class="inline-fields"><input aria-label="${attr(i.name)}現有數量" type="number" min="0" step="any" value="${fmt(stock(i))}" data-stock="${attr(i.key)}"><select aria-label="${attr(i.name)}保存方式" data-storage="${attr(i.key)}"><option value="">未記錄</option><option value="冷藏" ${state.storage[i.key]?.method==='冷藏'?'selected':''}>冷藏</option><option value="冷凍" ${state.storage[i.key]?.method==='冷凍'?'selected':''}>冷凍</option><option value="常溫" ${state.storage[i.key]?.method==='常溫'?'selected':''}>常溫</option></select><input aria-label="${attr(i.name)}包裝標示期限" type="date" data-expiry="${attr(i.key)}" value="${attr(state.storage[i.key]?.expiry||'')}"></span></div>`).join(''):'<p class="note">選完本週菜色後會出現食材。</p>'}</div></div><div class="two-col"><div class="panel"><h2>備菜安排</h2>${all.length?all.map(i=>`<div class="summary-line"><span>${esc(i.name)} · ${fmt(i.qty)} ${esc(i.unit)}</span><strong>${esc(i.prep||'依食譜處理')}</strong></div>`).join(''):'<p class="note">尚無備菜內容。</p>'}</div><div class="panel"><h2>保存提醒</h2><div class="callout warm">先分餐處理生肉，與即食食品及蔬菜分開。預計較晚煮的肉可盡早冷凍；完整蔬菜依包裝與狀況保存，切菜以烹煮當天為優先。</div><p class="note">冷藏建議以 4°C 以下為參考；生雞肉與絞肉通常 1–2 天、熟食冷藏通常 3–4 天。這是一般參考，個別食材仍應看包裝標示、購入時間及實際狀態。<br><a href="https://www.foodsafety.gov/food-safety-charts/cold-food-storage-charts" target="_blank" rel="noopener noreferrer">查看 FoodSafety.gov 冷藏保存表 ↗</a></p></div></div>`}
const nutrients=[['energy','熱量','kcal'],['protein','蛋白質','g'],['carbs','碳水化合物','g'],['fat','脂肪','g'],['fiber','膳食纖維','g'],['sodium','鈉','mg']];
function nutrition(entries){return nutrients.map(([key,label,unit])=>{const known=entries.filter(r=>Number.isFinite(r.nutrition?.[key]));return {key,label,unit,known:known.length,sum:known.reduce((n,r)=>n+r.nutrition[key],0)}})}
function summaryPage(){const recipes=selected(),completed=state.plan.filter(x=>x.done).map(x=>x.recipe),priced=recipes.filter(r=>Number.isFinite(r.cost)),base=Number(state.baseline)||300;const data=nutrition(recipes);app.innerHTML=heading('WEEKLY OUTLOOK','費用與營養','分清每餐食材分攤成本與真正採買支出；營養僅計入已填數值。')+`<div class="metrics"><div class="metric"><span>每餐平均預估</span><strong>${priced.length?money(total(priced)/priced.length):'待補'}</strong><small>${priced.length} / ${recipes.length} 道已填成本</small></div><div class="metric"><span>本週七餐預估</span><strong>${costText(recipes)}</strong><small>依食譜每份成本加總</small></div><div class="metric"><span>已完成餐點成本</span><strong>${costText(completed)}</strong><small>${completed.length} 餐已煮；仍為食譜估價</small></div></div><div class="two-col"><div class="panel"><h2>營養攝取估算</h2><p class="note">這裡是所選七餐的資料，不代表全天飲食。只有菜色填入可靠營養值後才會加總；未填的部分不能當作 0。</p>${data.map(n=>`<div class="summary-line"><span>${n.label}<small class="muted">　${n.known}/${recipes.length} 餐有數值</small></span><strong>${n.known?fmt(n.sum)+' '+n.unit:'待補'}${Number.isFinite(state.targets[n.key])&&n.known===recipes.length&&recipes.length?'<br><small class="muted">與七餐目標差 '+fmt(Math.max(0,state.targets[n.key]*recipes.length-n.sum))+' '+n.unit+'</small>':''}</strong></div>`).join('')}<p class="note">若要比較營養目標，請先補齊七餐數值，再填寫每餐參考目標；此處不推定個人需求量。</p><div class="form-grid">${nutrients.map(([key,label,unit])=>`<label class="field">${label}每餐參考目標（${unit}）<input type="number" min="0" step="any" data-target="${key}" value="${Number.isFinite(state.targets[key])?state.targets[key]:''}" placeholder="選填"></label>`).join('')}</div></div><div class="panel"><h2>跟外食比一比</h2><label class="field">假設每餐外食花費（NT$）<input id="baseline" type="number" min="0" step="1" value="${base}"></label><div class="callout warm" style="margin-top:18px">${recipes.length&&allPriced(recipes)?`如果 ${recipes.length} 餐外食每餐 ${money(base)}，總共 ${money(base*recipes.length)}；自己煮的食材分攤成本預估 ${money(total(recipes))}，${base*recipes.length>=total(recipes)?'差額約 '+money(base*recipes.length-total(recipes)):'比假設外食高約 '+money(total(recipes)-base*recipes.length)}。為自己煮飯，也是在替荷包留點呼吸空間。😊`:'把本週菜色的成本補齊，就能算出與外食的預估差額。'}</div><p class="note">食譜價格是每份估算，不等於到店採買金額；包裝剩餘、米飯、調味料與實際價格可能尚未計入。</p><h3>每餐明細</h3>${state.plan.length?state.plan.map((x,i)=>`<div class="summary-line"><span>${i+1}. ${esc(x.recipe.name)} ${x.done?'✓':''}</span><strong>${money(x.recipe.cost)}</strong></div>`).join(''):'<p class="note">尚未選本週菜色。</p>'}</div></div>`}
function recipesPage(){app.innerHTML=heading('YOUR RECIPE BOOK','菜色總覽','獨立管理想吃的菜。修改這裡，不會改動已經選好的本週七餐。',btn('create','＋ 新增菜色'))+`<div class="callout">把想吃的菜慢慢存進來；下次選新的一週時就有更多選擇。此處編輯與刪除不會覆蓋當週的食譜快照。</div>${toolbar()}${grid(state.recipes,'library')}`;bindSearch()}
function render(){page=location.hash.slice(1)||'plan';if(!['plan','today','shopping','summary','recipes'].includes(page))page='plan';$('#navigation').querySelectorAll('a').forEach(a=>{a.classList.toggle('active',a.dataset.page===page);if(a.dataset.page===page)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});({plan:planPage,today:todayPage,shopping:shoppingPage,summary:summaryPage,recipes:recipesPage})[page]()}
function showDialog(html){$('#dialog-content').innerHTML=html;dialog.showModal()}
function detail(r,index=null,library=false){const missing=r.ingredients.filter(i=>stock(i)<i.qty),frozen=r.ingredients.filter(i=>stock(i)>0&&state.storage[invKey(i.name,i.unit)]?.method==='冷凍');showDialog(`<div class="modal-head"><div><div class="page-kicker">${esc(r.category||'家常菜')} · ${esc(r.emoji||'🍽️')}</div><h2>${esc(r.name)}</h2><span class="muted">${esc(r.description||'')}</span></div><button class="close" data-action="close" aria-label="關閉">×</button></div><div class="modal-body"><div class="modal-stats"><span>每份成本：${money(r.cost)}</span><span>約 ${esc(r.time||'?')} 分鐘</span><span>營養：${nutrients.every(([k])=>Number.isFinite(r.nutrition?.[k]))?'已填完整':'部分或全部待補'}</span></div><div class="callout">${missing.length?'尚缺 '+missing.map(i=>esc(i.name)+' '+fmt(Math.max(0,i.qty-stock(i)))+esc(i.unit)).join('、'):'依登記庫存，食材足夠'}。${frozen.length?'已登記冷凍：'+frozen.map(i=>esc(i.name)).join('、')+'；烹煮前需安全解凍。':'未登記需要解凍的庫存。'}此提示不限制抽卡與選菜。</div><h3>食材與備菜方式</h3>${r.ingredients.map(i=>`<div class="summary-line"><span>${esc(i.name)} · ${fmt(i.qty)} ${esc(i.unit)}<small class="muted">　現有 ${fmt(stock(i))} ${esc(i.unit)}${state.storage[invKey(i.name,i.unit)]?.expiry?' · 標示期限 '+esc(state.storage[invKey(i.name,i.unit)].expiry):''}</small></span><strong>${esc(i.prep||'依食譜處理')}</strong></div>`).join('')}<h3>烹煮步驟</h3><ol>${r.steps.map(s=>`<li>${esc(s)}</li>`).join('')}</ol><h3>保存提醒</h3><p class="note">${esc(r.storage||'依食材包裝標示及實際狀態保存；生熟分開。')}</p><h3>每份營養估算</h3><div class="summary-list">${nutrients.map(([k,label,unit])=>`<div class="summary-line"><span>${label}</span><strong>${Number.isFinite(r.nutrition?.[k])?fmt(r.nutrition[k])+' '+unit:'待補'}</strong></div>`).join('')}</div><p class="note">食譜與價格為初始示例；營養值需要有來源的資料才能填入。</p><div class="button-row">${index!==null?btn('complete','完成這餐','button',`data-index="${index}"`):''}${library?btn('edit','編輯菜色','button secondary',`data-id="${attr(r.id)}"`)+btn('delete','刪除菜色','button danger',`data-id="${attr(r.id)}"`):''}</div></div>`)}
function ingredientRow(i={name:'',qty:1,unit:'g',prep:''}){return `<div class="ingredient-edit"><input name="ing-name" aria-label="食材名稱" placeholder="食材名稱" value="${attr(i.name)}" required><input name="ing-qty" aria-label="食材用量" type="number" min="0.001" step="any" value="${attr(i.qty)}" required><input name="ing-unit" aria-label="食材單位" placeholder="g / 顆" value="${attr(i.unit)}" required><input name="ing-prep" aria-label="處理方式" placeholder="切絲、切片…" value="${attr(i.prep||'')}"><button type="button" class="button ghost small" data-action="remove-ingredient" aria-label="移除這項食材">×</button></div>`}
function form(id=null){const r=state.recipes.find(x=>x.id===id);editingId=id;showDialog(`<div class="modal-head"><div><div class="page-kicker">RECIPE BOOK</div><h2>${r?'編輯菜色':'新增菜色'}</h2></div><button class="close" data-action="close" aria-label="關閉">×</button></div><div class="modal-body"><form id="recipe-form"><div class="form-grid"><label class="field">菜名<input name="name" required maxlength="80" value="${attr(r?.name||'')}"></label><label class="field">分類<input name="category" maxlength="30" value="${attr(r?.category||'家常菜')}"></label><label class="field">代表符號<input name="emoji" maxlength="6" value="${attr(r?.emoji||'🍽️')}"></label><label class="field">烹煮時間（分鐘）<input name="time" type="number" min="1" max="1440" value="${attr(r?.time||30)}" required></label><label class="field">每份估計成本（NT$，選填）<input name="cost" type="number" min="0" step="any" value="${r?.cost??''}"></label><label class="field full">簡介<input name="description" maxlength="200" value="${attr(r?.description||'')}"></label></div><div class="section-heading"><h2>每份食材</h2><button type="button" class="button secondary small" data-action="add-ingredient">＋ 增加食材</button></div><div id="ingredient-rows">${(r?.ingredients?.length?r.ingredients:[{name:'',qty:1,unit:'g'}]).map(ingredientRow).join('')}</div><div class="form-grid"><label class="field full">烹煮步驟（每行一步）<textarea name="steps" required>${esc(r?.steps?.join('\n')||'')}</textarea></label><label class="field full">保存與備菜提醒<textarea name="storage">${esc(r?.storage||'')}</textarea></label></div><div class="section-heading"><h2>每份營養數值</h2><span>選填；有可靠資料再填</span></div><div class="form-grid">${nutrients.map(([key,label,unit])=>`<label class="field">${label}（${unit}）<input name="n-${key}" type="number" min="0" step="any" value="${r?.nutrition?.[key]??''}" placeholder="尚無資料"></label>`).join('')}</div><p class="note">營養值請參考食品包裝或可靠的營養資料。空白表示未知，不會算成零。</p><div class="button-row" style="margin-top:20px"><button type="submit" class="button">儲存菜色</button>${btn('close','取消','button ghost')}</div></form></div>`)}
function handleForm(e){e.preventDefault();const f=e.target,fd=new FormData(f),name=String(fd.get('name')||'').trim(),ingredients=[...f.querySelectorAll('.ingredient-edit')].map(row=>({name:row.querySelector('[name=ing-name]').value.trim(),qty:Number(row.querySelector('[name=ing-qty]').value),unit:row.querySelector('[name=ing-unit]').value.trim(),prep:row.querySelector('[name=ing-prep]').value.trim()}));if(!name||!ingredients.length||ingredients.some(i=>!i.name||!i.unit||!Number.isFinite(i.qty)||i.qty<=0)){toast('請填好菜名和至少一項有效食材。');return}const steps=String(fd.get('steps')||'').split('\n').map(x=>x.trim()).filter(Boolean);if(!steps.length){toast('請填寫至少一步烹煮方式。');return}const nutrition={};for(const [k] of nutrients){const value=String(fd.get('n-'+k)||'').trim();if(value!=='')nutrition[k]=Number(value)}const cost=String(fd.get('cost')||'').trim();const data={id:editingId||crypto.randomUUID(),name,category:String(fd.get('category')||'家常菜').trim()||'家常菜',emoji:String(fd.get('emoji')||'🍽️').trim()||'🍽️',time:Number(fd.get('time')),cost:cost===''?null:Number(cost),description:String(fd.get('description')||'').trim(),ingredients,steps,storage:String(fd.get('storage')||'').trim(),nutrition};if(editingId){const i=state.recipes.findIndex(x=>x.id===editingId);if(i<0)return;state.recipes[i]=data}else state.recipes.push(data);save();dialog.close();render();toast('菜色已儲存。本週已選的餐次不受影響。')}
app.addEventListener('change',e=>{if(e.target.id==='baseline'){const v=Number(e.target.value);if(Number.isFinite(v)&&v>=0){state.baseline=v;save();render()}}if(e.target.dataset.shop){state.checked[e.target.dataset.shop]=e.target.checked;save();render()}if(e.target.dataset.stock){const v=Number(e.target.value);if(Number.isFinite(v)&&v>=0){state.inventory[e.target.dataset.stock]=v;save();render()}}if(e.target.dataset.storage){state.storage[e.target.dataset.storage]??={};state.storage[e.target.dataset.storage].method=e.target.value;save();render()}if(e.target.dataset.expiry){state.storage[e.target.dataset.expiry]??={};state.storage[e.target.dataset.expiry].expiry=e.target.value;save();render()}if(e.target.dataset.target){const v=e.target.value.trim();if(v==='')delete state.targets[e.target.dataset.target];else if(Number(v)>=0)state.targets[e.target.dataset.target]=Number(v);save();render()}});
document.addEventListener('submit',e=>{if(e.target.id==='recipe-form')handleForm(e)});
document.addEventListener('click',e=>{if(e.target===dialog){dialog.close();return}const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action,id=b.dataset.id,i=Number(b.dataset.index);switch(a){
case 'filter':category=b.dataset.category;render();break;
case 'add':if(state.plan.length>=7){toast('本週已選滿七餐。');break}const r=state.recipes.find(x=>x.id===id);if(!r)break;state.plan.push({id:crypto.randomUUID(),recipe:clone(r),done:false});state.checked={};save();render();toast('已加入本週七餐');break;
case 'remove-plan':if(state.plan[i]&&!state.plan[i].done){state.plan.splice(i,1);state.checked={};save();render()}break;
case 'draw':{const list=remaining();if(list.length){candidateId=list[Math.floor(Math.random()*list.length)].id;render();toast('翻出一道本週還沒煮的菜！')}break}
case 'view':if(state.plan[i]&&!state.plan[i].done)detail(state.plan[i].recipe,i);break;
case 'view-library':{const r=state.recipes.find(x=>x.id===id);if(r)detail(r,null,true);break}
case 'complete':{const slot=state.plan[i];if(!slot||slot.done)break;if(!confirm('確認已煮好這餐？會從已登記的庫存扣除實際使用量。'))break;for(const ing of slot.recipe.ingredients){const key=invKey(ing.name,ing.unit);state.inventory[key]=Math.max(0,Number(state.inventory[key]||0)-ing.qty)}slot.done=true;slot.finishedAt=new Date().toISOString();candidateId=null;save();dialog.close();render();toast('完成一餐，好好吃飯！');break}
case 'new-week':if(confirm('開始新的一週？本週七餐與購物勾選紀錄會清空；菜色庫與現有食材會保留。')){state.plan=[];state.checked={};state.week++;candidateId=null;save();render()}break;
case 'create':form();break;
case 'edit':dialog.close();form(id);break;
case 'delete':{const r=state.recipes.find(x=>x.id===id);if(!r)break;if(confirm('確定刪除「'+r.name+'」？已選本週七餐會保留當時的菜色內容。')){state.recipes=state.recipes.filter(x=>x.id!==id);save();dialog.close();render();toast('菜色已從總覽移除')}break}
case 'add-ingredient':$('#ingredient-rows').insertAdjacentHTML('beforeend',ingredientRow());break;
case 'remove-ingredient':b.closest('.ingredient-edit').remove();break;
case 'close':dialog.close();break;
}});
window.addEventListener('hashchange',()=>{search='';category='全部';render()});render();
